// Preview body inserted into the existing component closure by build-compact-controls.py.
function Demo(){
  const [label,setLabel]=useState('复制'); const [icon,setIcon]=useState('copy'); const [width,setWidth]=useState('auto');
  const actions=[{id:'edit',icon:'square-pen',label:'编辑'},{id:'share',icon:'share-2',label:'分享'},{id:'copy',icon:'copy',label:'复制'},{id:'download',icon:'download',label:'下载'}];
  return <div className="demo-page"><header className="demo-header"><h1 className="demo-title">ActionChip 操作块</h1><p className="demo-subtitle">ActionChip · 图标可选 · 自适应或固定宽度 · 4 个可验证交互状态</p></header>
   <section className="demo-section"><div className="demo-section-header"><h2 className="demo-section-name">Configurator</h2><span className="demo-section-tag">实时配置</span></div><p className="demo-section-desc">只暴露组件实际支持的 label、icon 和 width；Hover、Pressed、Focus 请在右侧标本上操作。</p><div className="preview-configurator"><div className="preview-controls"><label className="button-control"><span>Label</span><input value={label} onChange={e=>setLabel(e.target.value)} /></label><label className="button-control"><span>Icon</span><span className="button-select-wrap"><select value={icon} onChange={e=>setIcon(e.target.value)}><option value="">无图标</option><option value="copy">copy</option><option value="share-2">share-2</option><option value="download">download</option></select></span></label><label className="button-control"><span>Width</span><span className="button-select-wrap"><select value={width} onChange={e=>setWidth(e.target.value)}><option value="auto">Auto</option><option value="96px">96px</option><option value="160px">160px</option><option value="100%">100%</option></select></span></label></div><div className="preview-live"><ActionChip label={label||'操作'} icon={icon||undefined} width={width==='auto'?undefined:width}/></div></div></section>
   <section className="demo-section"><div className="demo-section-header"><h2 className="demo-section-name">ActionChip</h2><span className="demo-section-tag">Default / Hover / Pressed / Focus</span></div><p className="demo-section-desc">默认品牌 10% 底色；可用鼠标和 Tab 键体验真实交互。</p><div className="demo-grid demo-grid-2"><div className="demo-item"><h3 className="demo-item-title">Gallery · Auto width</h3><div className="demo-chip-row">{actions.map(a=><ActionChip key={a.id} icon={a.icon} label={a.label}/>)}</div></div><div className="demo-item"><h3 className="demo-item-title">Gallery · Fixed width</h3><div className="demo-chip-row"><ActionChip icon="download" label="导出" width={96}/><ActionChip icon="cloud-upload" label="上传到云端" width={96}/><ActionChip icon="settings" label="配置" width={96}/></div></div><div className="demo-item"><h3 className="demo-item-title">No icon / truncation</h3><div className="demo-chip-row demo-chip-row-fixed"><ActionChip label="仅文字操作"/><ActionChip icon="file-text" label="一键导出全部检测报告并同步到云端空间"/></div></div></div></section>
   <section className="demo-section preview-contract"><h2 className="demo-section-name">State matrix</h2><p className="preview-summary">ActionChip 没有 disabled prop；可验证状态来自 CSS 交互伪类。</p><div className="preview-state-grid">{['Default','Hover','Pressed','Focus'].map(state=><div className={'preview-state-card preview-action-chip-state-'+state.toLowerCase()} key={state}><ActionChip icon="copy" label="复制"/><span>{state}</span></div>)}</div></section>
   <section className="demo-section preview-contract"><h2 className="demo-section-name">Color spec</h2><div className="preview-table-wrap"><table className="preview-table preview-table--color"><thead><tr><th>Variant</th><th>State</th><th>Background</th><th>Outline</th><th>Text</th></tr></thead><tbody>{['Default','Hover','Pressed','Focus'].map((state,i)=><tr className={i===0?'preview-group-start':''} key={state}>{i===0?<th rowSpan={4} className="preview-variant">ActionChip</th>:null}<td className="preview-state">{state}</td><td><code>{state==='Default'?'--brand-10':state==='Hover'?'--color-interactive-hover':state==='Pressed'?'--color-interactive-pressed':'同 Default'}</code></td><td>{state==='Focus'?<code>--focus-ring</code>:<span className="preview-same">同 Default</span>}</td><td><code>--color-font-emphasize</code></td></tr>)}</tbody></table></div></section>
   <section className="demo-section preview-contract"><h2 className="demo-section-name">Token contract</h2><div className="preview-table-wrap"><table className="preview-table"><thead><tr><th>Property</th><th>Value</th><th>Token / rule</th></tr></thead><tbody><tr><th>Height</th><td>24px</td><td><code>--spacing-6</code></td></tr><tr><th>Typography</th><td>12px / 20px · Medium</td><td><code>--font-size-sm</code></td></tr><tr><th>Icon / gap</th><td>14px / 4px</td><td>Icon omitted when <code>icon</code> is empty</td></tr><tr><th>Padding / radius</th><td>0 8px / full</td><td><code>--radius-full</code></td></tr></tbody></table></div></section>
   <section className="demo-section preview-contract"><h2 className="demo-section-name">API contract</h2><div className="preview-table-wrap"><table className="preview-table preview-api"><thead><tr><th>Prop</th><th>Contract</th></tr></thead><tbody><tr><th>label</th><td>必填展示文案；长文本在受限宽度下省略。</td></tr><tr><th>icon</th><td>可选图标名；不传时仅渲染文字。</td></tr><tr><th>width</th><td>数字转为 px，字符串可传 CSS 宽度，缺省为 auto。</td></tr><tr><th>onClick / className</th><td>保留原生按钮回调与宿主扩展类名。</td></tr></tbody></table></div></section>
  </div>;
 }
