// Preview body inserted into the existing component closure by build-compact-controls.py.
function Demo(){
  const [shape,setShape]=useState('square'); const [state,setState]=useState('unchecked'); const [label,setLabel]=useState('允许通知');
  const selected=state==='checked'||state==='disabled-on'; const disabled=state.startsWith('disabled');
  const states=[{key:'unchecked',label:'未选中',checked:false},{key:'checked',label:'选中',checked:true},{key:'disabled-off',label:'禁用 · 未选中',checked:false,disabled:true},{key:'disabled-on',label:'禁用 · 选中',checked:true,disabled:true}];
  return <div className="demo-page"><header className="demo-header"><h2 className="preview-panel-title">Checkbox 勾选组件</h2><p className="demo-subtitle">Checkbox · Square / Circle · Checked / Unchecked · Disabled · 8 个形状状态组合</p></header>
   <section className="demo-section"><div className="demo-section-header"><h2 className="demo-section-name">Configurator</h2><span className="demo-section-tag">实时配置</span></div><p className="demo-section-desc">形状、状态和标签均映射到组件实际 props；键盘 Space / Enter 可切换可用标本。</p><div className="preview-configurator"><div className="preview-controls"><label className="button-control"><span>Shape</span><span className="button-select-wrap"><select value={shape} onChange={e=>setShape(e.target.value)}><option value="square">Square · 方形</option><option value="circle">Circle · 圆形</option></select></span></label><label className="button-control"><span>State</span><span className="button-select-wrap"><select value={state} onChange={e=>setState(e.target.value)}>{states.map(item=><option key={item.key} value={item.key}>{item.label}</option>)}</select></span></label><label className="button-control"><span>Label</span><input value={label} onChange={e=>setLabel(e.target.value)} /></label></div><div className="preview-live"><Checkbox shape={shape} checked={selected} disabled={disabled} label={label||undefined} onChange={next=>setState(next?'checked':'unchecked')}/></div></div></section>
   <section className="demo-section"><div className="demo-section-header"><h2 className="demo-section-name">Gallery · Shape × State</h2><span className="demo-section-tag">8 combinations</span></div><p className="demo-section-desc">容器 24×24，实际方框 20×20；禁用态在对应状态基础上整体 40% 不透明度。</p><div className="cbx-demo-matrix"><div className="cbx-demo-cell cbx-demo-head"/>{states.map(item=><div className="cbx-demo-cell cbx-demo-head" key={item.key}>{item.label}</div>)}{['square','circle'].map(item=><Fragment key={item}><div className="cbx-demo-cell cbx-demo-head cbx-demo-rowhead">{item==='square'?'方形':'圆形'}</div>{states.map(value=><div className="cbx-demo-cell" key={item+value.key}><Checkbox shape={item} checked={value.checked} disabled={value.disabled} onChange={()=>{}}/></div>)}</Fragment>)}</div></section>
   <section className="demo-section"><div className="demo-section-header"><h2 className="demo-section-name">Controlled multi-select</h2><span className="demo-section-tag">交互</span></div><p className="demo-section-desc">checked + onChange 由外部 state 驱动；禁用项不会改变计数。</p><CheckboxDemoList/></section>
   <section className="demo-section preview-contract"><h2 className="demo-section-name">Color spec</h2><div className="preview-table-wrap"><table className="preview-table preview-table--color"><thead><tr><th>Variant</th><th>State</th><th>Background</th><th>Outline</th><th>Text</th></tr></thead><tbody>{states.map((item,i)=><tr className={i===0?'preview-group-start':''} key={item.key}>{i===0?<th rowSpan={4} className="preview-variant">Square / Circle</th>:null}<td className="preview-state">{item.label}</td><td><code>{item.checked?'--color-comp-background-emphasize':'--color-fg-unchecked'}</code></td><td><code>{item.disabled?'同 Default':'--color-icon-tertiary'}</code></td><td>{item.disabled?<span className="preview-same">同 Default · opacity 40%</span>:<code>--on-surface</code>}</td></tr>)}</tbody></table></div></section>
   <section className="demo-section preview-contract"><h2 className="demo-section-name">Token contract</h2><div className="preview-table-wrap"><table className="preview-table"><thead><tr><th>Property</th><th>Value</th><th>Token / rule</th></tr></thead><tbody><tr><th>Control box</th><td>24px container / 20px box</td><td>实际可视框由 <code>--border-width-thin</code> 描边</td></tr><tr><th>Shape</th><td>Square 4px / Circle full</td><td><code>--radius-sm</code> / <code>--radius-full</code></td></tr><tr><th>Checked mark</th><td>15px icon</td><td>白色勾 + container 5% 内描边</td></tr><tr><th>Disabled</th><td>整体 opacity 40%</td><td>保留对应 checked 外观</td></tr></tbody></table></div></section>
   <section className="demo-section preview-contract"><h2 className="demo-section-name">API contract</h2><div className="preview-table-wrap"><table className="preview-table preview-api"><thead><tr><th>Prop</th><th>Contract</th></tr></thead><tbody><tr><th>shape</th><td><code>square</code> 或 <code>circle</code>，默认 square。</td></tr><tr><th>checked / defaultChecked</th><td>支持受控与非受控；checked 传入后由外部 state 驱动。</td></tr><tr><th>disabled</th><td>禁用点击与键盘交互，tabIndex 变为 -1。</td></tr><tr><th>label / onChange</th><td>label 可省略；onChange 接收下一个 boolean 值。</td></tr></tbody></table></div></section>
  </div>;
 }
